"""add ingredient cost_source and cost_updated_at

Mirrors nutrition_source / nutrition_updated_at: a label for where a price
came from ("manual", "AI estimate ...") plus when it was set. See
backend/ingredient_enrichment.py.

Revision ID: 530e710128ee
Revises: 582b0dc46fca
Create Date: 2026-08-22 20:43:53.851662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '530e710128ee'
down_revision: Union[str, Sequence[str], None] = '582b0dc46fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('cost_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ingredient', sa.Column('cost_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'cost_updated_at')
    op.drop_column('ingredient', 'cost_source')
    # ### end Alembic commands ###
