"""add volume-based measuring to ingredients

Lets a pantry item be priced and shopped for by volume instead of weight —
most liquids (milk, stock, oil, wine) are sold and shelf-priced per litre,
and forcing them through a density guess just to get a cost was both
unnecessary and a source of error the density might not deserve. See
backend/models.py's MeasureKind and backend/shopping.py's module docstring.

Five additive, nullable-or-defaulted columns; `measure_kind` follows the
existing VARCHAR-not-native-enum pattern (ingredient.source,
shoppingitem.unit) so it needs no `CREATE TYPE` on Postgres.

Revision ID: 9f515fcf77aa
Revises: f3d89f936ab8
Create Date: 2026-08-23 01:56:07.464255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f515fcf77aa'
down_revision: Union[str, Sequence[str], None] = 'f3d89f936ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('measure_kind', sa.Enum('weight', 'volume', name='measurekind', native_enum=False, length=16), server_default='weight', nullable=False))
    op.add_column('ingredient', sa.Column('package_size_ml', sa.Float(), nullable=True))
    op.add_column('ingredient', sa.Column('cost_per_litre_cents', sa.Integer(), nullable=True))
    op.add_column('recipeingredient', sa.Column('volume_ml', sa.Float(), nullable=True))
    op.add_column('shoppingitem', sa.Column('volume_ml', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoppingitem', 'volume_ml')
    op.drop_column('recipeingredient', 'volume_ml')
    op.drop_column('ingredient', 'cost_per_litre_cents')
    op.drop_column('ingredient', 'package_size_ml')
    op.drop_column('ingredient', 'measure_kind')
    # ### end Alembic commands ###
