"""add cook lists and shopping list

Revision ID: f3d89f936ab8
Revises: 530e710128ee
Create Date: 2026-08-22 22:03:11.163067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f3d89f936ab8'
down_revision: Union[str, Sequence[str], None] = '530e710128ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cook_date', sa.Date(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cooklist_cook_date'), 'cooklist', ['cook_date'], unique=False)
    op.create_table('cooklistrecipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cook_list_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['cook_list_id'], ['cooklist.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cooklistrecipe_cook_list_id'), 'cooklistrecipe', ['cook_list_id'], unique=False)
    op.create_index(op.f('ix_cooklistrecipe_recipe_id'), 'cooklistrecipe', ['recipe_id'], unique=False)
    op.create_table('shoppingitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weight_grams', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.Enum('g', 'kg', 'mg', 'ml', 'l', 'cup', 'tbsp', 'dsp', 'tsp', 'fl_oz', 'oz', 'lb', 'piece', 'slice', 'clove', 'bunch', 'sprig', 'can', 'pinch', 'to_taste', name='measureunit', native_enum=False, length=16), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'cook_list', name='shoppingitemsource', native_enum=False, length=16), server_default='manual', nullable=False),
    sa.Column('cook_list_id', sa.Integer(), nullable=True),
    sa.Column('contributions', sa.JSON(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cook_list_id'], ['cooklist.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shoppingitem_cook_list_id'), 'shoppingitem', ['cook_list_id'], unique=False)
    op.create_index(op.f('ix_shoppingitem_ingredient_id'), 'shoppingitem', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_shoppingitem_is_checked'), 'shoppingitem', ['is_checked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shoppingitem_is_checked'), table_name='shoppingitem')
    op.drop_index(op.f('ix_shoppingitem_ingredient_id'), table_name='shoppingitem')
    op.drop_index(op.f('ix_shoppingitem_cook_list_id'), table_name='shoppingitem')
    op.drop_table('shoppingitem')
    op.drop_index(op.f('ix_cooklistrecipe_recipe_id'), table_name='cooklistrecipe')
    op.drop_index(op.f('ix_cooklistrecipe_cook_list_id'), table_name='cooklistrecipe')
    op.drop_table('cooklistrecipe')
    op.drop_index(op.f('ix_cooklist_cook_date'), table_name='cooklist')
    op.drop_table('cooklist')
    # ### end Alembic commands ###
